name: bevert
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_ai: ^2.3.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  speech_to_text: ^7.2.0
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.2.3
  pdf: ^3.10.8
  share_plus: ^11.0.0
  audio_waveforms: ^1.3.0
  equatable: ^2.0.7
  go_router: ^16.0.0
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3
  uuid: ^4.5.1
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  disable-swift-package-manager: true
  assets:
    - .env
    - assets/fonts/NotoSansKR-Regular.ttf

