name: bevert
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # firebase
  firebase_core: ^3.15.2
  firebase_ai: ^2.3.0

  # network
  dio: ^5.9.0

  # permisson
  permission_handler: ^12.0.1

  # Sound & Record
  record: ^6.0.0

  # config
  flutter_dotenv: ^5.2.1
  go_router: ^16.0.0
  get_it: ^8.0.3

  # state management
  flutter_bloc: ^9.1.1

  # Database
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.9.1

  # Share
  pdf: ^3.10.8
  share_plus: ^11.0.0

  # etc
  equatable: ^2.0.7
  uuid: ^4.5.1
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6
  flutter_speed_dial: ^7.0.0
  toastification: ^3.0.3
  pull_down_button: ^0.10.2
  table_calendar: ^3.2.0
  vad: ^0.0.6
  audio_waveforms: ^1.3.0
  http_parser: ^4.1.2

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: "assets/splash/splash_light.png"
  image_dark: "assets/splash/splash_dark.png"
  background_image: "assets/splash/splash_bg_light.png"
  background_image_dark: "assets/splash/splash_bg_dark.png"
  android_12:
    color: "#1B77EC"
    color_dark: "#0D1117"
    image: "assets/splash/android_light.png"
    image_dark: "assets/splash/android_dark.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  disable-swift-package-manager: true
  assets:
    - .env
    - assets/fonts/NotoSansKR-Regular.ttf
    - assets/splash/
    - assets/icon/

